name: Sync Secrets to Azure App Settings

on:
  workflow_dispatch:

jobs:
  update-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update App Settings
        run: |
          az functionapp config appsettings set \
            --name macspotbackend \
            --resource-group MacSpotRG \
            --settings \
            MS365_CLIENT_ID='${{ secrets.MS365_CLIENT_ID }}' \
            MS365_CLIENT_SECRET='${{ secrets.MS365_CLIENT_SECRET }}' \
            MS365_TENANT_ID='${{ secrets.MS365_TENANT_ID }}' \
            MS365_USER_EMAIL='${{ secrets.MS365_USER_EMAIL }}' \
            APPLE_MAPS_TEAM_ID='${{ secrets.APPLE_MAPS_TEAM_ID }}' \
            APPLE_MAPS_KEY_ID='${{ secrets.APPLE_MAPS_KEY_ID }}' \
            APPLE_MAPS_PRIVATE_KEY='${{ secrets.APPLE_MAPS_PRIVATE_KEY }}' \
            CALDAV_USER='${{ secrets.CALDAV_USER }}' \
            CALDAV_PASSWORD='${{ secrets.CALDAV_PASSWORD }}' \
            CALDAV_CALENDAR_URL='${{ secrets.CALDAV_CALENDAR_URL }}'
            PGUSER='${{ secrets.PGUSER }}' \
            PGHOST='${{ secrets.PGHOST }}' \
            PGPASSWORD='${{ secrets.PGPASSWORD }}' \
            PGDATABASE='${{ secrets.PGDATABASE }}' \
            PGPORT='${{ secrets.PGPORT }}'