name: Sync Secrets to Azure App Settings

on:
  workflow_dispatch:

jobs:
  update-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update Function App Settings (macspotbackend)
        run: |
          az functionapp config appsettings set \
            --name macspotbackend \
            --resource-group MacSpotRG \
            --settings \
            MS365_CLIENT_ID='${{ secrets.MS365_CLIENT_ID }}' \
            MS365_CLIENT_SECRET='${{ secrets.MS365_CLIENT_SECRET }}' \
            MS365_TENANT_ID='${{ secrets.MS365_TENANT_ID }}' \
            MS365_USER_EMAIL='${{ secrets.MS365_USER_EMAIL }}' \
            APPLE_MAPS_TEAM_ID='${{ secrets.APPLE_MAPS_TEAM_ID }}' \
            APPLE_MAPS_KEY_ID='${{ secrets.APPLE_MAPS_KEY_ID }}' \
            APPLE_MAPS_PRIVATE_KEY='${{ secrets.APPLE_MAPS_PRIVATE_KEY }}' \
            CALDAV_USER='${{ secrets.CALDAV_USER }}' \
            CALDAV_PASSWORD='${{ secrets.CALDAV_PASSWORD }}' \
            CALDAV_CALENDAR_URL='${{ secrets.CALDAV_CALENDAR_URL }}' \
            PGUSER='${{ secrets.PGUSER }}' \
            PGHOST='${{ secrets.PGHOST }}' \
            PGPASSWORD='${{ secrets.PGPASSWORD }}' \
            PGDATABASE='${{ secrets.PGDATABASE }}' \
            PGPORT='${{ secrets.PGPORT }}' \
            GRAPH_CLIENT_ID='${{ secrets.GRAPH_CLIENT_ID }}' \
            GRAPH_CLIENT_SECRET='${{ secrets.GRAPH_CLIENT_SECRET }}' \
            GRAPH_TENANT_ID='${{ secrets.GRAPH_TENANT_ID }}' \
            GRAPH_USER_ID='${{ secrets.GRAPH_USER_ID }}' \
            DEBUG='${{ secrets.DEBUG }}' \
            MSGRAPH_WEBHOOK_URL='${{ secrets.MSGRAPH_WEBHOOK_URL }}' \
            ZOOM_ACCOUNT_ID ='${{ secrets.ZOOM_ACCOUNT_ID }}' \
            ZOOM_CLIENT_ID='${{ secrets.ZOOM_CLIENT_ID }}' \
            ZOOM_CLIENT_SECRET ='${{ secrets.ZOOM_CLIENT_SECRET }}' \
            ZOOM_USER_ID='${{ secrets.ZOOM_USER_ID }}' \

